name: CI

on:
  push:
    branches:
      - 'own-master'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout LiveSplit
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Fetch history
        run: git fetch --prune --unshallow --no-recurse-submodules

      - name: Checkout head_ref
        if: ${{ github.head_ref != '' }}
        run: git checkout -b ${{ github.head_ref }} || git checkout ${{ github.head_ref }}

      - name: Set up .NET environment
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x'

      - name: Build LiveSplit
        run: >
          dotnet build
          -v m
          -c Release
          -p:DebugType=None
          .\LiveSplit.slnx

      - name: Run tests
        run: >
          dotnet test
          -v m
          -c Release
          --no-restore --no-build
          .\LiveSplit.slnx

      - name: Upload build as an artifact
        uses: actions/upload-artifact@v7
        with:
          name: LiveSplit_Build
          path: .\artifacts\build\release
